/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator.visor;
import calculator.controller.CalculatorController;
import calculator.enums.EnumOperacao;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author Gabriel
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private CalculatorController calculatorController;
    
    private EnumOperacao ultimaOperacao;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        calculatorController = new CalculatorController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btApagar = new javax.swing.JButton();
        btAC = new javax.swing.JButton();
        btPrimo = new javax.swing.JButton();
        btRaiz = new javax.swing.JButton();
        btQuadrado = new javax.swing.JButton();
        btPorcentagem = new javax.swing.JButton();
        btPositivoNegativo = new javax.swing.JButton();
        btDividir = new javax.swing.JButton();
        btSete = new javax.swing.JButton();
        btOito = new javax.swing.JButton();
        btNove = new javax.swing.JButton();
        btMultiplicar = new javax.swing.JButton();
        btQuatro = new javax.swing.JButton();
        btCinco = new javax.swing.JButton();
        btSeis = new javax.swing.JButton();
        btSubtrair = new javax.swing.JButton();
        btUm = new javax.swing.JButton();
        btDois = new javax.swing.JButton();
        btTres = new javax.swing.JButton();
        btSomar = new javax.swing.JButton();
        btZero = new javax.swing.JButton();
        btZeroZero = new javax.swing.JButton();
        btVirgula = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        OutPutMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfValor.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValor.setText("0,00");
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(0, 4, 6, 8));

        btApagar.setText("←");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });
        jPanel1.add(btApagar);

        btAC.setText("AC");
        btAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btACActionPerformed(evt);
            }
        });
        jPanel1.add(btAC);

        btPrimo.setText("Primo");
        btPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimoActionPerformed(evt);
            }
        });
        jPanel1.add(btPrimo);

        btRaiz.setText("√");
        btRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRaizActionPerformed(evt);
            }
        });
        jPanel1.add(btRaiz);

        btQuadrado.setText("x²");
        btQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuadradoActionPerformed(evt);
            }
        });
        jPanel1.add(btQuadrado);

        btPorcentagem.setText("%");
        btPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPorcentagemActionPerformed(evt);
            }
        });
        jPanel1.add(btPorcentagem);

        btPositivoNegativo.setText("+/-");
        jPanel1.add(btPositivoNegativo);

        btDividir.setText("/");
        btDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDividirActionPerformed(evt);
            }
        });
        jPanel1.add(btDividir);

        btSete.setText("7");
        btSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeteActionPerformed(evt);
            }
        });
        jPanel1.add(btSete);

        btOito.setText("8");
        btOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOitoActionPerformed(evt);
            }
        });
        jPanel1.add(btOito);

        btNove.setText("9");
        btNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoveActionPerformed(evt);
            }
        });
        jPanel1.add(btNove);

        btMultiplicar.setText("X");
        btMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btMultiplicar);

        btQuatro.setText("4");
        btQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuatroActionPerformed(evt);
            }
        });
        jPanel1.add(btQuatro);

        btCinco.setText("5");
        btCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCincoActionPerformed(evt);
            }
        });
        jPanel1.add(btCinco);

        btSeis.setText("6");
        btSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeisActionPerformed(evt);
            }
        });
        jPanel1.add(btSeis);

        btSubtrair.setText("-");
        btSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtrairActionPerformed(evt);
            }
        });
        jPanel1.add(btSubtrair);

        btUm.setText("1");
        btUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUmActionPerformed(evt);
            }
        });
        jPanel1.add(btUm);

        btDois.setText("2");
        btDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoisActionPerformed(evt);
            }
        });
        jPanel1.add(btDois);

        btTres.setText("3");
        btTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTresActionPerformed(evt);
            }
        });
        jPanel1.add(btTres);

        btSomar.setText("+");
        btSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomarActionPerformed(evt);
            }
        });
        jPanel1.add(btSomar);

        btZero.setText("0");
        btZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZeroActionPerformed(evt);
            }
        });
        jPanel1.add(btZero);

        btZeroZero.setText("00");
        btZeroZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZeroZeroActionPerformed(evt);
            }
        });
        jPanel1.add(btZeroZero);

        btVirgula.setText(",");
        btVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVirgulaActionPerformed(evt);
            }
        });
        jPanel1.add(btVirgula);

        btIgual.setText("=");
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });
        jPanel1.add(btIgual);

        OutPutMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutPutMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OutPutMessage)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OutPutMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfValor)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomarActionPerformed
        calculatorController.realizaOperacao(EnumOperacao.SOMA, stringToDouble(tfValor.getText()));
        ultimaOperacao = EnumOperacao.SOMA;
        limpa();
    }//GEN-LAST:event_btSomarActionPerformed

    private void btACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btACActionPerformed
        limpa();
        calculatorController.zerar();
    }//GEN-LAST:event_btACActionPerformed

    private void btMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicarActionPerformed
        calculatorController.realizaOperacao(EnumOperacao.MULTIPLICACAO, stringToDouble(tfValor.getText()));
        ultimaOperacao = EnumOperacao.MULTIPLICACAO;
        limpa();
    }//GEN-LAST:event_btMultiplicarActionPerformed

    private void btRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRaizActionPerformed
        Double valor = stringToDouble(tfValor.getText());
        Double resultado = calculatorController.realizaOperacao(EnumOperacao.RAIZ, valor);
        tfValor.setText(DoubleToString(resultado));
        OutPutMessage.setText(calculatorController.getMessage());
    }//GEN-LAST:event_btRaizActionPerformed

    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        calculatorController.realizaOperacao(ultimaOperacao, stringToDouble(tfValor.getText()));
        tfValor.setText(DoubleToString(calculatorController.getTotal()));
    }//GEN-LAST:event_btIgualActionPerformed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
        String str = tfValor.getText();
        StringBuilder w = new StringBuilder(str);
        str = String.valueOf( w.deleteCharAt(str.length() - 1) );
        tfValor.setText(str);
    }//GEN-LAST:event_btApagarActionPerformed

    private void btSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeteActionPerformed
        digita("7");
    }//GEN-LAST:event_btSeteActionPerformed

    private void btOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOitoActionPerformed
        digita("8");
    }//GEN-LAST:event_btOitoActionPerformed

    private void btNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoveActionPerformed
       digita("9");
    }//GEN-LAST:event_btNoveActionPerformed

    private void btQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuatroActionPerformed
       digita("4");
    }//GEN-LAST:event_btQuatroActionPerformed

    private void btCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCincoActionPerformed
       digita("5");
    }//GEN-LAST:event_btCincoActionPerformed

    private void btSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeisActionPerformed
       digita("6");
    }//GEN-LAST:event_btSeisActionPerformed

    private void btUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUmActionPerformed
       digita("1");
    }//GEN-LAST:event_btUmActionPerformed

    private void btDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoisActionPerformed
       digita("2");
    }//GEN-LAST:event_btDoisActionPerformed

    private void btTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTresActionPerformed
       digita("3");
    }//GEN-LAST:event_btTresActionPerformed

    private void btZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZeroActionPerformed
      digita("0");
    }//GEN-LAST:event_btZeroActionPerformed

    private void btZeroZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZeroZeroActionPerformed
     digita("00");
    }//GEN-LAST:event_btZeroZeroActionPerformed

    private void btVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVirgulaActionPerformed
     digita(",");
    }//GEN-LAST:event_btVirgulaActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed

    private void btSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtrairActionPerformed
        calculatorController.realizaOperacao(EnumOperacao.SUBTRACAO, stringToDouble(tfValor.getText()));
        ultimaOperacao = EnumOperacao.SUBTRACAO;
        limpa();
    }//GEN-LAST:event_btSubtrairActionPerformed

    private void btDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDividirActionPerformed
        calculatorController.realizaOperacao(EnumOperacao.DIVISAO, stringToDouble(tfValor.getText()));
        ultimaOperacao = EnumOperacao.DIVISAO;
        limpa();
    }//GEN-LAST:event_btDividirActionPerformed

    private void btPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimoActionPerformed
        Double valor = stringToDouble(tfValor.getText());
        Double resultado = calculatorController.realizaOperacao(EnumOperacao.PRIMO, valor);
        tfValor.setText(DoubleToString(resultado));
        OutPutMessage.setText(calculatorController.getMessage());
    }//GEN-LAST:event_btPrimoActionPerformed

    private void btPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPorcentagemActionPerformed
Double valorDoVisor = stringToDouble(this.tfValor.getText());
        Double valorPercentual;

        if (this.ultimaOperacao == null) {
            valorPercentual = valorDoVisor / 100.0;
            
            this.calculatorController.realizaOperacao(null, valorPercentual);

        } else {
            if (this.ultimaOperacao == EnumOperacao.SOMA || this.ultimaOperacao == EnumOperacao.SUBTRACAO) {
                Double totalAtual = this.calculatorController.getTotal();
                valorPercentual = totalAtual * (valorDoVisor / 100.0);
                
            } else {
                valorPercentual = valorDoVisor / 100.0;
            }

            this.calculatorController.realizaOperacao(this.ultimaOperacao, valorPercentual);

            Double resultadoFinal = this.calculatorController.getTotal(); // 10.0 / 0.1 = 100.0

            this.tfValor.setText(DoubleToString(resultadoFinal));
            this.ultimaOperacao = null;
    }//GEN-LAST:event_btPorcentagemActionPerformed
    }
    private void btQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuadradoActionPerformed
        Double valor = stringToDouble(tfValor.getText());
        Double resultado = calculatorController.realizaOperacao(EnumOperacao.QUADRADO, valor);
        tfValor.setText(DoubleToString(resultado));
        OutPutMessage.setText(calculatorController.getMessage());
        limpa();
    }//GEN-LAST:event_btQuadradoActionPerformed

    private void OutPutMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutPutMessageActionPerformed

    }//GEN-LAST:event_OutPutMessageActionPerformed
    
    private String DoubleToString(Double numero){
        if (numero != null) {
        if (numero == numero.longValue()) {
            DecimalFormat formato = new DecimalFormat("#,##0", new DecimalFormatSymbols(new Locale("pt", "BR")));
            return formato.format(numero);
        } else {
            DecimalFormat formato = new DecimalFormat("#,##0.##########", new DecimalFormatSymbols(new Locale("pt", "BR")));
            return formato.format(numero);
            }
        }
        return "";
    }
    
    private Double stringToDouble(String numero){
        NumberFormat nf = NumberFormat.getInstance(new Locale("pt", "BR"));
        Double dv = 0.0;
        try{
            dv = nf.parse(numero).doubleValue();
        } catch(ParseException ex){
            System.err.println("Erro de parsing no número: " + numero);
        }
        return dv;
    }
    
    private void limpa(){
        tfValor.setText("0,00");
        OutPutMessage.setText("");
    }
    
    private void digita(String caractere){
        if(tfValor.getText().equals("0,00")){
            tfValor.setText(caractere);
        }else{
         if(caractere.equals(",")&& tfValor.getText().contains(",")){
             
         }else{
            tfValor.setText(tfValor.getText().concat(caractere));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OutPutMessage;
    private javax.swing.JButton btAC;
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btCinco;
    private javax.swing.JButton btDividir;
    private javax.swing.JButton btDois;
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btMultiplicar;
    private javax.swing.JButton btNove;
    private javax.swing.JButton btOito;
    private javax.swing.JButton btPorcentagem;
    private javax.swing.JButton btPositivoNegativo;
    private javax.swing.JButton btPrimo;
    private javax.swing.JButton btQuadrado;
    private javax.swing.JButton btQuatro;
    private javax.swing.JButton btRaiz;
    private javax.swing.JButton btSeis;
    private javax.swing.JButton btSete;
    private javax.swing.JButton btSomar;
    private javax.swing.JButton btSubtrair;
    private javax.swing.JButton btTres;
    private javax.swing.JButton btUm;
    private javax.swing.JButton btVirgula;
    private javax.swing.JButton btZero;
    private javax.swing.JButton btZeroZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}

